name: 🪄 Auto Fix & Format Code

on:
  workflow_dispatch: # زرار تدوس عليه يشغل التصليح أوتوماتيك

permissions:
  contents: write

jobs:
  auto-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Auto-Format Dart
        run: |
          if [ -d "gui" ]; then
            cd gui
            dart format .
            cd ..
          fi
          if [ -d "core" ]; then
            cd core
            dart format .
            cd ..
          fi

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto format dart files"
